//HintName: Typely.Generators.Tests.Typely.Configurations.Username.g.cs
// <auto-generated>This file was generated by Typely.</auto-generated>
using System;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using Typely.Core;
using Typely.Core.Converters;

#nullable enable

namespace Typely.Generators.Tests.Typely.Configurations
{
    [JsonConverter(typeof(TypelyJsonConverter<string, Username>))]
    public partial struct Username : ITypelyValue<string, Username>, IEquatable<Username>, IComparable<Username>, IComparable
    {
        public string Value { get; private set; }

        public Username() => throw new Exception("Parameterless constructor is not allowed.");

        public Username(string value)
        {
            TypelyValue.ValidateAndThrow<string, Username>(value);
            Value = value;
        }

        public static ValidationError? Validate(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(Username));

            return null;
        }

        public static Username From(string value) => new(value);

        public static bool TryFrom(string value, [MaybeNullWhen(false)] out Username typelyType, out ValidationError? validationError)
        {
            validationError = Validate(value);
            var isValid = validationError == null;
            typelyType = default;
            if (isValid)
            {
                typelyType.Value = value;
            }
            return isValid;
        }

        public override string ToString() => Value.ToString();

        public static bool operator !=(Username left, Username right) => !(left == right);

        public static bool operator ==(Username left, Username right) => left.Equals(right);

        public override int GetHashCode() => Value.GetHashCode();

        public bool Equals(Username other) => Value.Equals(other.Value);

        public override bool Equals([NotNullWhen(true)] object? obj) => obj is Username && Equals((Username)obj);

        public int CompareTo(Username other) => Value.CompareTo(other.Value);

        public int CompareTo(object? obj) => obj is not Username ? 1 : CompareTo((Username)obj!);

        public static explicit operator string(Username value) => value.Value;
    }
}