//HintName: Election.Votes.g.cs
// <auto-generated>This file was generated by Typely.</auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using Typely.Core;
using Typely.Core.Converters;
using Typely.Generators.Tests.Typely.Configurations;

#nullable enable

namespace Election
{
    [TypeConverter(typeof(TypelyTypeConverter<bool, Votes>))]
    [JsonConverter(typeof(TypelyJsonConverter<bool, Votes>))]
    public partial struct Votes : ITypelyValue<bool, Votes>, IEquatable<Votes>, IComparable<Votes>, IComparable
    {
        public bool Value { get; private set; }

        public Votes() => throw new Exception("Parameterless constructor is not allowed.");

        public Votes(bool value)
        {
            TypelyValue.ValidateAndThrow<bool, Votes>(value);
            Value = value;
        }

        public static ValidationError? Validate(bool value)
        {
            if (value == default)
            {
                return ValidationErrorFactory.Create(value, "ERR-001", "The value cannot be empty", "Presidency vote");
            }

            if (value.Equals(false))
            {
                return ValidationErrorFactory.Create(value, "NotEqual", ErrorMessages.NotEqual, "Presidency vote",
                    new Dictionary<string, object?>
                    {
                        { "ComparisonValue", false },
                    });
            }

            if (!(value== true))
            {
                return ValidationErrorFactory.Create(value, "Must", LocalizedMessages.CustomMessage, "Presidency vote");
            }

            if (!(!value.Equals(10)))
            {
                return ValidationErrorFactory.Create(value, "Must", A.CustomLocalization.Value, "Presidency vote");
            }

            return null;
        }

        public static Votes From(bool value) => new(value);

        public static bool TryFrom(bool value, [MaybeNullWhen(false)] out Votes typelyType, out ValidationError? validationError)
        {
            validationError = Validate(value);
            var isValid = validationError == null;
            typelyType = default;
            if (isValid)
            {
                typelyType.Value = value;
            }
            return isValid;
        }

        public override string ToString() => Value.ToString();

        public static bool operator !=(Votes left, Votes right) => !(left == right);

        public static bool operator ==(Votes left, Votes right) => left.Equals(right);

        public override int GetHashCode() => Value.GetHashCode();

        public bool Equals(Votes other) => Value.Equals(other.Value);

        public override bool Equals([NotNullWhen(true)] object? obj) => obj is Votes && Equals((Votes)obj);

        public int CompareTo(Votes other) => Value.CompareTo(other.Value);

        public int CompareTo(object? obj) => obj is not Votes ? 1 : CompareTo((Votes)obj!);

        public static explicit operator bool(Votes value) => value.Value;
    }
}