//HintName: UserId.g.cs
// <auto-generated>This file was generated by Typely.</auto-generated>
using Typely.Core;
using Typely.Core.Converters;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

#nullable enable

namespace UserAggregate
{
    [JsonConverter(typeof(TypelyJsonConverter<Int32, UserId>))]
    public partial struct UserId : ITypelyValue<Int32, UserId>, IEquatable<UserId>
    {
        public Int32 Value { get; private set; }

        public UserId() => throw new Exception("Parameterless constructor is not allowed.");

        public UserId(Int32 value)
        {
            TypelyValue.ValidateAndThrow<Int32, UserId>(value);
            Value = value;
        }

        public static ValidationError? Validate(Int32 value)
        {
            if (!EqualityComparer<int>.Default.Equals(value, 0))
            {
                return ValidationErrorFactory.Create(value, "NotEmpty", ErrorMessages.NotEmpty, "Owner identifier");
            }

            if (!EqualityComparer<int>.Default.Equals(value, 100))
            {
                return ValidationErrorFactory.Create(value, "ERR001", "{Name} cannot be equal to {ComparisonValue}.", "Owner identifier",
                    new Dictionary<string, object?>
                    {
                        { "ComparisonValue", 100 },
                    });
            }

            return null;
        }

        public static UserId From(Int32 value) => new(value);

        public static bool TryFrom(Int32 value, [MaybeNullWhen(false)] out UserId typelyType, out ValidationError? validationError)
        {
            validationError = Validate(value);
            var isValid = validationError == null;
            typelyType = default;
            if (isValid)
            {
                typelyType.Value = value;
            }
            return isValid;
        }

        public override string ToString() => Value.ToString();

        public static bool operator !=(UserId left, UserId right) => !(left == right);

        public static bool operator ==(UserId left, UserId right) => left.Equals(right);

        public static bool operator !=(Int32 left, UserId right) => !(left == right);

        public static bool operator ==(Int32 left, UserId right) => left.Equals(right.Value);

        public static bool operator !=(UserId left, Int32 right) => !(left == right);

        public static bool operator ==(UserId left, Int32 right) => left.Value.Equals(right);

        public override int GetHashCode() => EqualityComparer<Int32>.Default.GetHashCode(Value);

        public override bool Equals([NotNullWhen(true)] object? obj) => obj is UserId && Equals((UserId)obj);

        public bool Equals(UserId other) => EqualityComparer<Int32>.Default.Equals(Value, other.Value);

        public static explicit operator Int32(UserId value) => value.Value;
    }
}