//HintName: Sunday.g.cs
// <auto-generated>This file was generated by Typely.</auto-generated>
using Typely.Core;
using Typely.Core.Converters;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

#nullable enable

namespace Typely.Generators.Tests.Typely.Configurations
{
    [JsonConverter(typeof(TypelyJsonConverter<string, Sunday>))]
    public partial class Sunday : ITypelyValue<string, Sunday>, IEquatable<Sunday>, IComparable<Sunday>, IComparable
    {
        public string Value { get; private set; }

        public Sunday() => throw new Exception("Parameterless constructor is not allowed.");

        public Sunday(string value)
        {
            TypelyValue.ValidateAndThrow<string, Sunday>(value);
            Value = value;
        }

        public static ValidationError? Validate(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(Sunday));

            if (value.Length < 1)
            {
                return ValidationErrorFactory.Create(value, "MinLength", ErrorMessages.MinLength, "Sunday",
                    new Dictionary<string, object?>
                    {
                        { "MinLength", 1 },
                    });
            }

            if (value.Length > 20)
            {
                return ValidationErrorFactory.Create(value, "MaxLength", ErrorMessages.MaxLength, "Sunday",
                    new Dictionary<string, object?>
                    {
                        { "MaxLength", 20 },
                    });
            }

            return null;
        }

        public static Sunday From(string value) => new(value);

        public static bool TryFrom(string value, [MaybeNullWhen(false)] out Sunday typelyType, out ValidationError? validationError)
        {
            validationError = Validate(value);
            var isValid = validationError == null;
            typelyType = default;
            if (isValid)
            {
                typelyType.Value = value;
            }
            return isValid;
        }

        public override string ToString() => Value.ToString();

        public static bool operator !=(Sunday left, Sunday right) => !(left == right);

        public static bool operator ==(Sunday left, Sunday right) => left.Equals(right);

        public override int GetHashCode() => Value.GetHashCode();

        public bool Equals(Sunday other) => Value.Equals(other.Value);

        public override bool Equals([NotNullWhen(true)] object? obj) => obj is Sunday && Equals((Sunday)obj);

        public int CompareTo(Sunday other) => Value.CompareTo(other.Value);

        public int CompareTo(object? obj) => obj is not Sunday ? 1 : CompareTo((Sunday)obj!);

        public static explicit operator string(Sunday value) => value.Value;
    }
}