//HintName: UserId.g.cs
// <auto-generated>This file was generated by Typely.</auto-generated>
using Typely.Core;
using Typely.Core.Converters;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

#nullable enable

namespace UserAggregate
{
    [JsonConverter(typeof(TypelyJsonConverter<String, UserId>))]
    public partial struct UserId : ITypelyValue<String, UserId>, IEquatable<UserId>, IComparable<UserId>, IComparable
    {
        public String Value { get; private set; }

        public UserId() => throw new Exception("Parameterless constructor is not allowed.");

        public UserId(String value)
        {
            TypelyValue.ValidateAndThrow<String, UserId>(value);
            Value = value;
        }

        public static ValidationError? Validate(String value)
        {
            if (value == null) throw new ArgumentNullException(nameof(UserId));

            if (string.IsNullOrWhiteSpace(value))
            {
                return ValidationErrorFactory.Create(value, "NotEmpty", ErrorMessages.NotEmpty, "Owner identifier");
            }

            if (value.Equals("100"))
            {
                return ValidationErrorFactory.Create(value, "ERR001", "{Name} cannot be equal to {ComparisonValue}.", "Owner identifier",
                    new Dictionary<string, object?>
                    {
                        { "ComparisonValue", "100" },
                    });
            }

            if (value.Length > 100)
            {
                return ValidationErrorFactory.Create(value, "MaxLength", ErrorMessages.MaxLength, "Owner identifier",
                    new Dictionary<string, object?>
                    {
                        { "MaxLength", 100 },
                    });
            }

            return null;
        }

        public static UserId From(String value) => new(value);

        public static bool TryFrom(String value, [MaybeNullWhen(false)] out UserId typelyType, out ValidationError? validationError)
        {
            validationError = Validate(value);
            var isValid = validationError == null;
            typelyType = default;
            if (isValid)
            {
                typelyType.Value = value;
            }
            return isValid;
        }

        public override string ToString() => Value.ToString();

        public static bool operator !=(UserId left, UserId right) => !(left == right);

        public static bool operator ==(UserId left, UserId right) => left.Equals(right);

        public override int GetHashCode() => Value.GetHashCode();

        public bool Equals(UserId other) => Value.Equals(other.Value);

        public override bool Equals([NotNullWhen(true)] object? obj) => obj is UserId && Equals((UserId)obj);

        public int CompareTo(UserId other) => Value.CompareTo(other.Value);

        public int CompareTo(object? obj) => obj is not UserId ? 1 : CompareTo((UserId)obj!);

        public static explicit operator String(UserId value) => value.Value;
    }
}