//HintName: Monday.g.cs
// <auto-generated>This file was generated by Typely.</auto-generated>
using Typely.Core;
using Typely.Core.Converters;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

#nullable enable

namespace Typely.Generators.Tests.Typely.Configurations
{
    [JsonConverter(typeof(TypelyJsonConverter<string, Monday>))]
    public partial class Monday : ITypelyValue<string, Monday>, IEquatable<Monday>, IComparable<Monday>, IComparable
    {
        public string Value { get; private set; }

        public Monday() => throw new Exception("Parameterless constructor is not allowed.");

        public Monday(string value)
        {
            TypelyValue.ValidateAndThrow<string, Monday>(value);
            Value = value;
        }

        public static ValidationError? Validate(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(Monday));

            if (value.Length < 1)
            {
                return ValidationErrorFactory.Create(value, "MinLength", ErrorMessages.MinLength, "Monday",
                    new Dictionary<string, object?>
                    {
                        { "MinLength", 1 },
                    });
            }

            if (value.Length > 20)
            {
                return ValidationErrorFactory.Create(value, "MaxLength", ErrorMessages.MaxLength, "Monday",
                    new Dictionary<string, object?>
                    {
                        { "MaxLength", 20 },
                    });
            }

            return null;
        }

        public static Monday From(string value) => new(value);

        public static bool TryFrom(string value, [MaybeNullWhen(false)] out Monday typelyType, out ValidationError? validationError)
        {
            validationError = Validate(value);
            var isValid = validationError == null;
            typelyType = default;
            if (isValid)
            {
                typelyType.Value = value;
            }
            return isValid;
        }

        public override string ToString() => Value.ToString();

        public static bool operator !=(Monday left, Monday right) => !(left == right);

        public static bool operator ==(Monday left, Monday right) => left.Equals(right);

        public override int GetHashCode() => Value.GetHashCode();

        public bool Equals(Monday other) => Value.Equals(other.Value);

        public override bool Equals([NotNullWhen(true)] object? obj) => obj is Monday && Equals((Monday)obj);

        public int CompareTo(Monday other) => Value.CompareTo(other.Value);

        public int CompareTo(object? obj) => obj is not Monday ? 1 : CompareTo((Monday)obj!);

        public static explicit operator string(Monday value) => value.Value;
    }
}