//HintName: UserId.g.cs
// <auto-generated>This file was generated by Typely.</auto-generated>
using Typely.Core;
using Typely.Core.Converters;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

#nullable enable

namespace Typely.Generators.Tests.Typely.Configurations
{
    [JsonConverter(typeof(TypelyJsonConverter<Int32, UserId>))]
    public partial struct UserId : ITypelyValue<Int32, UserId>
    {
        public Int32 Value { get; private set; }

        public UserId() => throw new Exception("Parameterless constructor is not allowed.");

        public UserId(Int32 value)
        {
            TypelyValue.ValidateAndThrow<Int32, UserId>(value);
            Value = value;
        }

        public static ValidationError? Validate(Int32 value)
        {
            if (!EqualityComparer<int>.Default.Equals(value, 0))
            {
                return ValidationErrorFactory.Create(value, "NotEmpty", ErrorMessages.NotEmpty, "UserId");
            }

            return null;
        }

        public static UserId From(Int32 value) => new(value);

        public static bool TryFrom(Int32 value, [MaybeNullWhen(false)] out UserId typelyType, out ValidationError? validationError)
        {
            validationError = Validate(value);
            var isValid = validationError == null;
            typelyType = default;
            if (isValid)
            {
                typelyType.Value = value;
            }
            return isValid;
        }
    }
}