<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
    <PackageReference Include="Typely.Core" Version="8.0.0" />
    <PackageReference Include="Typely.Generators" Version="1.8.0" />
    <PackageReference Include="ValueOf" Version="2.0.31" />
    <PackageReference Include="Vogen" Version="5.0.5" />
  </ItemGroup>
    
  <ItemGroup>
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage" />
  </ItemGroup>
</Project>
