<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>Typely: Unleashing the power of value object creation with a fluent Api. This package contains ASP.NET Core integration features.</Description>
    </PropertyGroup>

    <!-- Development reference -->
    <ItemGroup Condition="'$(Configuration)'=='Debug'">
        <ProjectReference Include="..\Typely.Core\Typely.Core.csproj" />
    </ItemGroup>

    <!-- Production reference -->
    <ItemGroup Condition="'$(Configuration)'!='Debug'">
        <PackageReference Include="Typely.Core" Version="$(VersionPrefix)" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <None Include="nuget-readme.md" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>
