using Microsoft.CodeAnalysis;

namespace FluentType.Generator.Generators
{
    [Generator]
    public class HelloWorldGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            string source = $@"// <auto-generated/>
using System;

namespace FluentType.Playground
{{
    public static class Class1
    {{
        static void HelloFrom(string name) =>
            Console.WriteLine($""Generator says: Hi from '{{name}}'"");
    }}
}}
";

            context.AddSource($"main.g.cs", source);
        }

        public void Initialize(GeneratorInitializationContext context)
        {
        }
    }
}
