name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore ./src/Typely.sln
      - name: Build
        run: dotnet build --configuration Release --no-restore ./src/Typely.sln
      - name: Test
        run: dotnet test --no-restore --verbosity normal ./src/Typely.sln
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
      - name: Create nuget packages
        run: |
          dotnet pack --configuration Release ./src/Typely.Core/Typely.Core.csproj
          dotnet pack --configuration Release ./src/Typely.Generators/Typely.Generators.csproj
      - name: Publish packages
        run: dotnet nuget push ./artifacts/*.nupkg